# Generated by Django 4.2.13 on 2024-05-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Место')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.CharField(verbose_name='Описание мероприятия')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prometheus.categories', verbose_name='Категория')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prometheus.spaces', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиша',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_reseved', models.CharField(max_length=255, verbose_name='Количество забронированных мест')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время бронирования')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prometheus.events')),
            ],
        ),
    ]
