# Generated by Django 4.2.13 on 2024-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название события'),
        ),
    ]
