# Generated by Django 4.2.13 on 2024-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlessons',
            name='group',
            field=models.CharField(choices=[('1', 'Ассорти'), ('2', 'Радость'), ('3', 'Родничок'), ('4', 'Наш дом'), ('5', '220 Вольт'), ('6', 'Виват')], verbose_name='Выберите коллектив'),
        ),
    ]
