# Generated by Django 4.2.13 on 2024-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0002_alter_firstlessons_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('post', models.TextField(blank=True, verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['time_create'],
            },
        ),
        migrations.AlterField(
            model_name='firstlessons',
            name='group',
            field=models.CharField(choices=[('1', 'Ассорти'), ('2', 'Радость'), ('3', 'Родничок'), ('4', 'Наш дом'), ('5', '220 Вольт'), ('6', 'Виват')], verbose_name='Коллектив'),
        ),
    ]
