# Generated by Django 4.2.13 on 2024-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0003_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sets_reseved',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_reserved',
            field=models.IntegerField(default=0, verbose_name='Количество забронированных мест'),
            preserve_default=False,
        ),
    ]
