# Generated by Django 4.2.13 on 2024-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0003_news_alter_firstlessons_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллектива')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='photos/group/', verbose_name='Фото 1')),
                ('image2', models.ImageField(upload_to='photos/group/', verbose_name='Фото 2')),
                ('image3', models.ImageField(upload_to='photos/group/', verbose_name='Фото 3')),
                ('image4', models.ImageField(upload_to='photos/group/', verbose_name='Фото 4')),
                ('image5', models.ImageField(upload_to='photos/group/', verbose_name='Фото 5')),
            ],
            options={
                'verbose_name': 'Коллектив',
                'verbose_name_plural': 'Коллективы',
                'ordering': ['id'],
            },
        ),
    ]
