# Generated by Django 4.2.13 on 2024-06-09 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0004_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlessons',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prometheus.groups', verbose_name='Коллектив'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post',
            field=models.TextField(blank=True, verbose_name='Пост'),
        ),
    ]
