# Generated by Django 4.2.13 on 2024-06-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prometheus', '0005_alter_firstlessons_group_alter_news_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['time'], 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
    ]
